// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "databaseOrderExposed": string;
      "databaseOrder": string;
      "fetchOnAdd": string;
      "autoUpdate": string;
      "autoUpdateCutoff": string;
      "useColors": string;
      "ignoredItems": string;
      "rateLimits": string;
      "googleScholarEndpoint": string;
      "semanticScholarApiKey": string;
      "debugLogging": boolean;
    };
  }
}
