pref('databaseOrderExposed', 'crossref,semanticscholar')
pref('databaseOrder', 'crossref,semanticscholar')
pref('fetchOnAdd', 'true')
pref('autoUpdate', 'never')
pref('autoUpdateCutoff', '6')
pref('useColors', 'color')
pref('ignoredItems', '{}')
pref('rateLimits', '{"crossref":1000,"semanticscholar":3000,"inspire":1000}')
